[rtpengine]
interface=185.83.210.134
foreground=true
log-stderr=true
listen-ng=12221
listen-udp=22222
port-min=50000
port-max=60000
recording-dir=/tmp
recording-method=pcap
recording-format=eth
log-level=6
delete-delay=0
MAX_SESSIONS=50000
